### ISSUE TITLE
Is there potential for an HHKB Hybrid model?

### ISSUE THREAD

**Issue by leftbones** [stefan-ess/hhkb_controller#2]
Not sure if it's even possible but it would be amazing to have a USB hub in my bluetooth Hybrid.

**Comment by 4pplet** [comment]
Hi! Sorry for the delayed response. There is no plans for adding support for the hybrid to this project (It only supports Pro 2). I am planning for a Hybrid controller running ZMK in the future, however, it will likely be without a hub
