### ISSUE TITLE
for hhkb bt

### ISSUE THREAD

**Issue by 3000ye** [stefan-ess/hhkb_controller#3]
你好，请问可以添加对hhkb bt 的支持嘛。
我手上只有bt版的，无法烧录固件。

**Comment by 4pplet** [comment]
Apologies for the late response. This project will only be for the HHKB Pro 2. There is work on getting the newer HHKBs to run QMK, since they have hardware capable of doing so. I believe this should also be valid for the HHKB BT.

https://geekhack.org/index.php?topic=106213.0
